<?php /**CSS Fields **/

if (get_field('ar_custom_css_on', 'option')) :
	//Add Options Page
	if( function_exists('acf_add_options_page') ) :
		acf_add_options_sub_page(array(
			'page_title' 	=> 'RealAdvantage Plus CSS',
			'menu_title'	=> 'Custom CSS',
			'menu_slug' 	=> 'customcss',
			'parent_slug'	=> 'realadvantage',
			'update_button'		=> __('Save Settings', 'acf'),
			'updated_message'	=> __('Your settings have been updated successfully.', 'acf'),
		));
	endif;

	//Add Fields
	if( function_exists('acf_add_local_field_group') ):
		acf_add_local_field_group(array(
			'key' => 'group_5e393fdb4baf1',
			'title' => 'Custom CSS',
			'fields' => array(
				array(
					'key' => 'field_5e39401b62f19',
					'label' => 'Main',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5e39405af0949',
					'label' => 'Main CSS',
					'name' => 'main_ar_css',
					'type' => 'acf_code_field',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '/*****************************	Enter CSS Rules Here	*****************************/',
					'placeholder' => '',
					'mode' => 'css',
					'theme' => 'mdn-like',
				),
				array(
					'key' => 'field_5e39418bf7927',
					'label' => 'Utilities',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5e394191f7928',
					'label' => 'Utilities CSS',
					'name' => 'utilities_ar_css',
					'type' => 'acf_code_field',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '/*****************************	Enter CSS Rules Here	*****************************/',
					'placeholder' => '',
					'mode' => 'css',
					'theme' => 'mdn-like',
				),
				array(
					'key' => 'field_5e3941a8f7929',
					'label' => 'IDX Widgets',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5e3941aef792a',
					'label' => 'IDX Widgets CSS',
					'name' => 'idx_widgets_ar_css',
					'type' => 'acf_code_field',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '/*****************************	Enter CSS Rules Here	*****************************/',
					'placeholder' => '',
					'mode' => 'css',
					'theme' => 'mdn-like',
				),
				array(
					'key' => 'field_5e3941eef792c',
					'label' => 'Communities',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5e3941edf792b',
					'label' => 'Communities',
					'name' => 'coms_ar_css',
					'type' => 'acf_code_field',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '/*****************************	Enter CSS Rules Here	*****************************/',
					'placeholder' => '',
					'mode' => 'css',
					'theme' => 'mdn-like',
				),
				array(
					'key' => 'field_5e394246f792d',
					'label' => 'Blog',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5e39424ef792e',
					'label' => 'Blog CSS',
					'name' => 'blog_ar_css',
					'type' => 'acf_code_field',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '/*****************************	Enter CSS Rules Here	*****************************/',
					'placeholder' => '',
					'mode' => 'css',
					'theme' => 'mdn-like',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'customcss',
					),
				),
			),
			'menu_order' => 5,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
		));
	endif;
endif;