<?php 

if( function_exists('acf_add_local_field_group') ):

//features tabs

$avadaTab = array(
	array(
		'key' => 'field_5cdaa6ecd214e',
		'label' => 'Avada Settings',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'placement' => 'left',
		'endpoint' => 0,
	),
	array(
		'key' => 'field_5cdaa49a46b56code',
		'label' => 'Activate AR CSS Fields',
		'name' => 'ar_custom_css_on',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_5cdaa49a46b56',
		'label' => 'Show Header top Bar on v7 Header',
		'name' => 'ar_header_top',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_5cdaa701d214f',
		'label' => 'Hide Fusion Branding',
		'name' => 'hide_fusion_branding',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_5cdbcebab9374',
		'label' => 'Replace Author Section With Author Block',
		'name' => 'ar_author_replace',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_5cece8a291333',
		'label' => 'Activate Smooth Scroll Anchor Links',
		'name' => 'ar_smooth_scroll',
		'type' => 'true_false',
		'instructions' => 'will not work with header v6',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_5cf5c5d0805a1',
		'label' => 'Replace social icons email with contact url',
		'name' => 'ar_replace_social_email',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_5df15eb554bf0',
		'label' => 'Use Text Logo',
		'name' => 'ar_use_text_logo',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_5df15ecd54bf1',
		'label' => 'Logo Content',
		'name' => 'ar_logo_content',
		'type' => 'repeater',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_5df15eb554bf0',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'collapsed' => 'field_5df15ef854bf3',
		'min' => 0,
		'max' => 0,
		'layout' => 'table',
		'button_label' => '',
		'sub_fields' => array(
			array(
				'key' => 'field_5df15edc54bf2',
				'label' => 'Tag',
				'name' => 'tag',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'h1' => 'h1',
					'h2' => 'h2',
					'h3' => 'h3',
					'h4' => 'h4',
					'h5' => 'h5',
					'h6' => 'h6',
					'p' => 'p',
				),
				'default_value' => array(
					0 => 'h3',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5df15ef854bf3',
				'label' => 'Text',
				'name' => 'text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
	),
);

$idxOption = array(
	array(
		'key' => 'field_5cda8f666bc7a',
		'label' => 'Replace Wordpress Posts Search Form with IDX Search Form?',
		'name' => 'ar_replace_search',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
);
$idxTab = array(
	array(
		'key' => 'field_5cdf19fb6a8dc',
		'label' => 'IDX Broker',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'placement' => 'left',
		'endpoint' => 0,
	),
	array(
		'key' => 'field_5cdf19f26a8db',
		'label' => 'IDX Account ID',
		'name' => 'idx_account_id',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_5cdf1a0a6a8dd',
		'label' => 'IDX Base Link (do not include trailing slash)',
		'name' => 'idx_account_url',
		'type' => 'url',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
	),
	array(
		'key' => 'field_5dff0827edae6',
		'label' => 'Activate RealAdvantage IDX Wrapper Codes?',
		'name' => 'ar_wrapcodes_active',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '40',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_5dff11b527389',
		'label' => 'Modals Theme',
		'name' => 'ar_wrapcodes_modals',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_5dff0827edae6',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '30',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'none' => 'None',
			'theme1' => 'IdahoLegacy.com',
		),
		'default_value' => array(
			0 => 'theme1',
		),
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_5dff0827edae62020',
		'label' => 'Use 2020 Theme Settings?',
		'name' => 'ar_idx2020theme_active',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_5dff0827edae6',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '30',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_5f6a5d32dea82agentfield',
		'label' => 'Agents Field Label',
		'name' => 'ar_idx_agents_field_label',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '100',
			'class' => '',
			'id' => '',
		),
		'default_value' => 'Working with an Agent?',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_5e06d90622731',
		'label' => 'Map Icons',
		'name' => 'map_icons',
		'type' => 'group',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_5dff0827edae6',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '100',
			'class' => '',
			'id' => '',
		),
		'layout' => 'block',
		'sub_fields' => array(
			array(
				'key' => 'field_5e06d91422732',
				'label' => 'Large',
				'name' => 'large',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5e06d92922733',
				'label' => 'Small',
				'name' => 'small',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
	),
);
$idxThemes2020 = array(
	array(
		'key' => 'field_5f6a4e9cdea70',
		'label' => '2020 Theme Settings',
		'name' => 'ar_idx2020theme_settings',
		'type' => 'group',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_5dff0827edae6',
					'operator' => '==',
					'value' => '1',
				),
				array(
					'field' => 'field_5dff0827edae62020',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'layout' => 'row',
		'sub_fields' => array(
			array(
				'key' => 'field_5f6a5aafdea71',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5f6a5abadea72',
						'label' => 'Align',
						'name' => 'align',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'center' => 'Center',
							'right' => 'Right',
						),
						'allow_null' => 0,
						'default_value' => 'center',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5f6a5b13dea73',
						'label' => 'Wrap',
						'name' => 'wrap',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'wrap' => 'Wrap',
							'no-wrap' => 'No Wrap',
						),
						'allow_null' => 0,
						'default_value' => 'wrap',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5f6a5b2bdea74',
						'label' => 'Direction',
						'name' => 'direction',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '34',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'row' => 'Row',
							'column' => 'Column',
						),
						'allow_null' => 0,
						'default_value' => 'row',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5f6a5b43dea75style',
						'label' => 'Border Style',
						'name' => 'border_style',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'solid' => 'Solid',
							'dotted' => 'Dotted',
							'dashed' => 'Dashed',
						),
						'default_value' => 'solid',
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5f6a5b43dea75',
						'label' => 'Border Width',
						'name' => 'border_width',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f6a5befdea76',
						'label' => 'Border Color',
						'name' => 'border_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '34',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_5f6a5c32dea77',
						'label' => 'Separator Width',
						'name' => 'sep_width',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f6a5c44dea78',
						'label' => 'Separator Max Width',
						'name' => 'sep_max_width',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f6a5c62dea79',
						'label' => 'Separator Order',
						'name' => 'sep_order',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '34',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5f6a5c7ddea7a',
				'label' => 'Tab',
				'name' => 'tab',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5f6a5c90dea7b',
						'label' => 'Border Color',
						'name' => 'border_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#e2e2e2',
					),
					array(
						'key' => 'field_5f6a5ccadea7d',
						'label' => 'Active Color',
						'name' => 'active_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_5f6a5cd9dea7e',
						'label' => 'Inactive Color',
						'name' => 'inactive_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '34',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#f9f9fb',
					),
					array(
						'key' => 'field_5f6a5cecdea7f',
						'label' => 'Font Size',
						'name' => 'font_size',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '1.4rem',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f6a5ca5dea7c',
						'label' => 'Accent Color',
						'name' => 'accent_color',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'primary' => 'Primary',
							'custom' => 'Custom',
						),
						'allow_null' => 0,
						'default_value' => 'primary',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5f6a5ca5dea7custom',
						'label' => 'Accent Color Custom',
						'name' => 'accent_color_custom',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5f6a5ca5dea7c',
									'operator' => '==',
									'value' => 'custom',
								),
							),
						),
						'wrapper' => array(
							'width' => '34',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#000000',
					),
				),
			),
			array(
				'key' => 'field_5f6a5d06dea80',
				'label' => 'General',
				'name' => 'general',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5f6a5d16dea81',
						'label' => 'Alternate Background Color',
						'name' => 'alt_bg',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#f5f5f5',
					),
					array(
						'key' => 'field_5f6a5d32dea82',
						'label' => 'Button Text Size',
						'name' => 'button_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '1.2rem',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f6a5d4cdea83',
						'label' => 'Captcha Display',
						'name' => 'captcha',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '34',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'none' => 'None',
							'block' => 'Block',
							'flex' => 'Flex',
						),
						'default_value' => 'none',
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
		),
	),
);
$idxModalsTheme1 =array(
	array(
		'key' => 'field_5dff13dfbcfa6',
		'label' => 'Theme1 Image',
		'name' => 'ar_wc_modals_theme1_img',
		'type' => 'image',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_5dff11b527389',
					'operator' => '==',
					'value' => 'theme1',
				),
			),
		),
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'return_format' => 'id',
		'preview_size' => 'medium',
		'library' => 'all',
		'min_width' => '',
		'min_height' => '',
		'min_size' => '',
		'max_width' => '',
		'max_height' => '',
		'max_size' => '',
		'mime_types' => '',
	),
	array(
		'key' => 'field_5dffbbdf2a766',
		'label' => 'Theme1 Styles',
		'name' => 'ar_wc_modals_theme1_styles',
		'type' => 'group',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_5dff0827edae6',
					'operator' => '==',
					'value' => '1',
				),
				array(
					'field' => 'field_5dff11b527389',
					'operator' => '==',
					'value' => 'theme1',
				),
			),
		),
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'layout' => 'block',
		'sub_fields' => array(
			array(
				'key' => 'field_5dffbd162a76b',
				'label' => 'Fonts',
				'name' => 'fonts',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5dffbd2a2a76c',
						'label' => 'Inputs',
						'name' => 'input',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5dffbd342a76d',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5dffbd392a76e',
						'label' => 'Button',
						'name' => 'button',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5dffbdab46a0c',
				'label' => 'Button Colors',
				'name' => 'button_colors',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5dffbdac46a0d',
						'label' => 'Standard',
						'name' => 'std',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5dffbdd346a10',
								'label' => 'Background',
								'name' => 'bg',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
							),
							array(
								'key' => 'field_5dffbde646a11',
								'label' => 'Border',
								'name' => 'border',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
							),
							array(
								'key' => 'field_5dffbdf446a12',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '34',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
							),
						),
					),
					array(
						'key' => 'field_5dffbe0746a13',
						'label' => 'Hover',
						'name' => 'hover',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5dffbe0846a14',
								'label' => 'Background',
								'name' => 'bg',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
							),
							array(
								'key' => 'field_5dffbe0846a15',
								'label' => 'Border',
								'name' => 'border',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
							),
							array(
								'key' => 'field_5dffbe0846a16',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '34',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
							),
						),
					),
					array(
						'key' => 'field_5dffc076c29a8',
						'label' => 'Secondary',
						'name' => 'secondary',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
					),
				),
			),
			array(
				'key' => 'field_5dffbfc8c29a4',
				'label' => 'Button Styles',
				'name' => 'button_styles',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5dffbfc8c29a5',
						'label' => 'Weight',
						'name' => 'weight',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'100' => '100',
							'200' => '200',
							'300' => '300',
							'400' => '400',
							'500' => '500',
							'600' => '600',
							'700' => '700',
							'800' => '800',
							'900' => '900',
						),
						'default_value' => '500',
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5dffbfc8c29a6',
						'label' => 'Border Width (px)',
						'name' => 'border',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5dffc0e6c29a9',
						'label' => 'Uppercase',
						'name' => 'uppercase',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
				),
			),
			array(
				'key' => 'field_5dffc22cc29aa',
				'label' => 'Extra Colors',
				'name' => 'extra',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5dffc22cc29ab',
						'label' => 'Input Border Color',
						'name' => 'input_border',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
					),
					array(
						'key' => 'field_5dffc22cc29ac',
						'label' => 'OR Color',
						'name' => 'or_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
					),
					array(
						'key' => 'field_5dffc22cc29ad',
						'label' => 'Link Color',
						'name' => 'link_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
					),
				),
			),
		),
	),
);
$featureFields = array(
	array(
		'key' => 'field_5cda8f896bc7b',
		'label' => 'API Keys',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'placement' => 'left',
		'endpoint' => 0,
	),
	array(
		'key' => 'field_5cda8f926bc7c',
		'label' => 'Walkscore ID',
		'name' => 'ar_walkscore',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_5cda8ff36bc80',
		'label' => 'Google Maps API Key',
		'name' => 'ar_gmap_key',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_5cda8fa96bc7d',
		'label' => 'FiveStar',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'placement' => 'left',
		'endpoint' => 0,
	),
	array(
		'key' => 'field_5cda8fb86bc7e',
		'label' => 'Activate FiveStar Automatic Republish Tool?',
		'name' => 'ar_activate_fivestar',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_5cda92be3586e',
		'label' => 'MatchHeight',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'placement' => 'left',
		'endpoint' => 0,
	),
	array(
		'key' => 'field_5cda92c73586f',
		'label' => 'matchHeight CSS Selectors',
		'name' => 'ar_match',
		'type' => 'repeater',
		'instructions' => 'Add CSS Selectors. Example: div.someClass',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'collapsed' => 'field_5cda92e435870',
		'min' => 0,
		'max' => 0,
		'layout' => 'table',
		'button_label' => 'Add Selector',
		'sub_fields' => array(
			array(
				'key' => 'field_5cda92e435870',
				'label' => 'Selector',
				'name' => 'selector',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
	),
	array(
		'key' => 'field_5ce042ca8fa60',
		'label' => 'Google Autocomplete',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'placement' => 'left',
		'endpoint' => 0,
	),
	array(
		'key' => 'field_5ce042e28fa61',
		'label' => 'Fields',
		'name' => 'ar_autocomplete',
		'type' => 'repeater',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'collapsed' => 'field_5ce0433f8fa63',
		'min' => 0,
		'max' => 0,
		'layout' => 'table',
		'button_label' => 'Add Selctor',
		'sub_fields' => array(
			array(
				'key' => 'field_5ce043188fa62',
				'label' => 'Type',
				'name' => 'type',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'class' => 'Class',
					'id' => 'ID',
					'name' => 'Name',
				),
				'default_value' => array(
					0 => 'class',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5ce0433f8fa63',
				'label' => 'Selector',
				'name' => 'selector',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '75',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
	),
	array(
		'key' => 'field_5ceb8f2e4eacd',
		'label' => 'RealAdvantage Updates',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'placement' => 'left',
		'endpoint' => 0,
	),
	array(
		'key' => 'field_5ceb8ee848b94',
		'label' => 'RealAdvantage Token',
		'name' => 'realadvantage_updates_token',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_5cef8850b6409',
		'label' => 'Activate Developer Mode',
		'name' => 'realadvantage_dev_mode',
		'type' => 'true_false',
		'instructions' => 'SETTING THIS VALUE TO TRUE WILL CONNECT YOU TO THE DEVELOPMENT SERVER. <Br/>This could cause your site to go down as untested features are live here. <b>DO NOT CHANGE</b>',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_5d00a44ca19a7',
		'label' => 'Choose Site',
		'name' => 'ar_client_file',
		'type' => 'select',
		'instructions' => '<strong>DO NOT CHANGE</strong> Activates specific custom code for each client theme as needed',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => ar_client_files(),
		'default_value' => array(
			0 => 'none',
		),
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 1,
		'ajax' => 0,
		'return_format' => 'value',
		'placeholder' => '',
	),
	array(
		'key' => 'field_5e09acba920b9',
		'label' => 'Choose Directory Site',
		'name' => 'ar_client_directory_tpl',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'default' => 'Default',
			'ballesterosgroup' => 'Ballesteros Group',
		),
		'default_value' => array(
			0 => 'default',
		),
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
);


if(shortcode_exists('idx-omnibar')) :
	$idxAllFields = array_merge($idxOption, $idxTab, $idxThemes2020, $idxModalsTheme1);
	$featureAllFields = array_merge($avadaTab, $idxAllFields, $featureFields);
else :
	$featureAllFields = array_merge($avadaTab, $featureFields);
endif;

acf_add_local_field_group(array(
	'key' => 'group_5cda8f3e43754',
	'title' => 'Enable Theme Features',
	'fields' => $featureAllFields,
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'features',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));


//location map
acf_add_local_field_group(array(
	'key' => 'group_5cda671125412',
	'title' => 'Walkscore and Schools',
	'fields' => array(
		array(
			'key' => 'field_5cda671d0a859',
			'label' => 'Map Location',
			'name' => 'location',
			'type' => 'google_map',
			'instructions' => 'This field is REQUIRED to set the location for the walkscore or schools shortcodes.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '150',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'avada_portfolio',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

//FiveStar
if(get_field('ar_activate_fivestar','option')) :
	acf_add_local_field_group(array(
		'key' => 'group_5cda866927ff1',
		'title' => 'Auto Blogging Tool',
		'fields' => array(
			array(
				'key' => 'field_5cda866fafcff',
				'label' => 'Activate Re-Publish?',
				'name' => 'activate_auto_updates',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5cda878d5d739',
				'label' => 'How Often?',
				'name' => 'auto_update_days',
				'type' => 'number',
				'instructions' => 'Recommended lowest value: 7 days (1 week)',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5cda866fafcff',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 30,
				'placeholder' => 'this many',
				'prepend' => 'Every',
				'append' => 'day(s)',
				'min' => '',
				'max' => '',
				'step' => 1,
			),
			array(
				'key' => 'field_5cda881b5d73a',
				'label' => 'Created By',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<p style="text-align:center;margin:0 auto;"><a href="https://www.agentreputation.net" target="_blank"><img src="/wp-content/themes/realadvantage-plus/realadvantage/img/ar-logo-2018.png" alt="Agent Reputation 5 Star Auto Blogging" style="max-width:100%;height:auto;" /></a></p>',
				'new_lines' => '',
				'esc_html' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 2,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
endif;

//Author Image
acf_add_local_field_group(array(
	'key' => 'group_5cdc87c5f167e',
	'title' => 'Author Image',
	'fields' => array(
		array(
			'key' => 'field_5cdc87def9d46',
			'label' => 'Profile Image',
			'name' => 'ar_wp_author_img',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'edit',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));




endif;