<?php //video post type fields

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5cef527a7b4f2',
	'title' => 'Video Settings',
	'fields' => array(
		array(
			'key' => 'field_5cef5282a7d3a',
			'label' => 'Type',
			'name' => 'type',
			'type' => 'button_group',
			'instructions' => 'Poster image will be required for uploaded videos',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'youtube' => 'YouTube',
				'vimeo' => 'Vimeo',
				'self' => 'Upload Video',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5cef52baa7d3b',
			'label' => 'YouTube Video ID',
			'name' => 'youtube_vid',
			'type' => 'text',
			'instructions' => 'Alphanumeric code at the end of your youtube video url. See <strong>bold</strong> sections in the urls below for example.<br/>https://www.youtube.com/watch?v=<strong>G0mncEl4nVU</strong><Br/>https://youtu.be/<strong>G0mncEl4nVU</strong>',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cef5282a7d3a',
						'operator' => '==',
						'value' => 'youtube',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => 'https://www.youtube.com/watch?v=',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5cef5337a7d3c',
			'label' => 'Vimeo Video ID',
			'name' => 'vimeo_vid',
			'type' => 'text',
			'instructions' => 'Alphanumeric code at the end of your vimeo video url. See <strong>bold</strong> sections in the url below for example.<br/>https://vimeo.com/<strong>333536837</strong>',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cef5282a7d3a',
						'operator' => '==',
						'value' => 'vimeo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => 'https://vimeo.com/',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5cef537ea7d3d',
			'label' => 'Video File',
			'name' => 'self_files',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cef5282a7d3a',
						'operator' => '==',
						'value' => 'self',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5cef53faa7d3f',
					'label' => 'MP4',
					'name' => 'mp4',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
				array(
					'key' => 'field_5cef540ca7d40',
					'label' => 'OGV',
					'name' => 'ogv',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'ogv',
				),
				array(
					'key' => 'field_5cef5424a7d41',
					'label' => 'WEBM',
					'name' => 'webm',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'webm',
				),
				array(
					'key' => 'field_5cef5458a7d42',
					'label' => 'Poster',
					'name' => 'poster',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'ar_videos',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;